//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Handle
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giros
    {
        public int id { get; set; }
        public int owner_id { get; set; }
        public decimal amount { get; set; }
        public System.DateTime create_date { get; set; }
        public string owner_type { get; set; }
    }
}
