//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Handle
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysClients:IClient
    {
        public int id { get; set; }
        public string client_name { get; set; }
        public System.DateTime birth_date { get; set; }
    }
}
